// app/terms/page.tsx
import Link from 'next/link';

export default function Terms() {
  return (
    <main className="min-h-screen bg-gray-50 p-8 md:p-20 font-sans text-slate-900">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="text-indigo-600 font-bold text-xs uppercase tracking-widest hover:underline mb-8 inline-block">
          &larr; Back to Tool
        </Link>

        <article className="bg-white p-10 md:p-16 rounded-3xl border border-slate-200 shadow-sm prose prose-slate max-w-none">
          <h1 className="text-4xl font-black text-slate-900 mb-6 tracking-tight">Terms of Service</h1>
          
          <p className="text-lg text-slate-600 leading-relaxed">
            By using <strong>LaraQuick JSON</strong>, you agree to the following terms and conditions. 
            Please read them carefully before using our conversion tool.
          </p>

          <h2 className="text-xl font-bold text-slate-800 mt-10">1. Use of the Tool</h2>
          <p className="text-slate-600">
            LaraQuick JSON is provided as a free tool for developers. You are responsible for verifying 
            the code generated before using it in production environments. We are not responsible for 
            any data loss or bugs caused by the use of the generated code.
          </p>

          <h2 className="text-xl font-bold text-slate-800 mt-8">2. Shared Content</h2>
          <p className="text-slate-600">
            When you use the "Save & Share" feature, you acknowledge that the content of your JSON 
            and the resulting schema will be stored in our database and will be accessible to anyone 
            who has the unique URL (slug). Do not share sensitive information such as passwords, 
            private keys, or personal data.
          </p>

          <h2 className="text-xl font-bold text-slate-800 mt-8">3. Intellectual Property</h2>
          <p className="text-slate-600">
            The code generated by the tool belongs to you. However, the design, branding, and 
            source code of LaraQuick JSON are the property of the site owners.
          </p>

          <h2 className="text-xl font-bold text-slate-800 mt-8">4. Disclaimer of Warranties</h2>
          <p className="text-slate-600 italic">
            "The service is provided 'as is' without warranty of any kind, either express or implied." 
            We do not guarantee that the tool will be available 100% of the time or that the 
            conversions will always be error-free.
          </p>

          <footer className="mt-12 pt-8 border-t border-slate-100 text-slate-400 text-xs uppercase font-bold tracking-widest">
            Last updated: March 2026
          </footer>
        </article>
      </div>
    </main>
  );
}